ConfigVars = {}
ConfigVars ['PastRunsEnabled'] = 1
ConfigVars ['PreProcessVideos'] = 1
ConfigVars ['DownloadURLS'] = 1
ConfigVars['DesiredFrames'] = 10
# 0 = Dont log anything
# 1 = Write to log only
# 2 = Write to console only
# 3 = Write to log and console
ConfigVars ['LogLevel'] = 2
